# Generated by Django 2.2.10 on 2022-11-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombrecargo', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_dpto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dpto', models.CharField(max_length=100)),
                ('tarifa_diaria', models.IntegerField()),
                ('direccion', models.CharField(max_length=20)),
                ('nro_dpto', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='departamentos')),
                ('img', models.BinaryField(blank=True, null=True)),
                ('img1', models.BinaryField(blank=True, null=True)),
                ('img2', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disp', models.AutoField(primary_key=True, serialize=False)),
                ('descr_estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'disponibilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioDpto',
            fields=[
                ('id_inv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_objeto', models.CharField(max_length=50)),
                ('cant_objeto', models.IntegerField()),
                ('valor_unitario_obj', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario_dpto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mant', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mant', models.CharField(max_length=50)),
                ('descripcion_mant', models.CharField(max_length=2000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('disponibilidad', models.IntegerField()),
                ('costo_mantencion', models.IntegerField()),
            ],
            options={
                'db_table': 'mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_inicial', models.IntegerField(blank=True, null=True)),
                ('diferencia_pago', models.IntegerField(blank=True, null=True)),
                ('total_pagar', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario_id', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=100)),
                ('celular', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioFunc',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254)),
                ('clave', models.CharField(max_length=40)),
                ('celular', models.IntegerField()),
                ('rut', models.CharField(max_length=14)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidopaterno', models.CharField(max_length=40)),
                ('apellidomaterno', models.CharField(max_length=40)),
                ('img', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario_func',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=6)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
    ]
